name: "Terraform Apply AWS Certificate Manager workflow"

on:
  push:
    branches:
      - master

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_ORGANIZATION }} # repository variable
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: ${{ vars.TF_WORKSPACE_ACM }} # repository variable
  CONFIG_DIRECTORY: "./acm"

jobs:
  terraform_create:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ${{env.CONFIG_DIRECTORY}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3 
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve -input=false

      - name: Terraform outputs (Important! Check this out!)
        id: outputs
        run:  |
          echo "Use these values to configure your DNS server. Add these values to your DNS database."
          echo "ATTENTION!!! If you use GoDaddy, please check this out: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-DNS-validation.html#troubleshooting-DNS-GoDaddy"
          echo "After set the values to you DNS server, please, wait until AWS finish validate the certificates."
          terraform output